version: "3.9"

services:

  gateway:
    build: ./API-Gateway
    container_name: gateway
    ports:
      - "8080:8080"
    networks:
      - sheshan

  order-service:
    build: ./BackEndServices/order-service
    container_name: order-service
    ports:
      - "8081:8081"
    networks:
      - sheshan

  inventory-service:
    build: ./BackEndServices/inventory-service
    container_name: inventory-service
    ports:
      - "8083:8083"
    networks:
      - sheshan

  payment-service:
    build: ./BackEndServices/payment-service
    container_name: payment-service
    ports:
      - "8082:8082"
    networks:
      - sheshan

networks:
  sheshan:
    name: sheshan.local