server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: http://inventory-service.sheshan.local:8083
          predicates:
            - Path=/inventory/**
        - id: payment-service
          uri: http://payment-service.sheshan.local:8082
          predicates:
            - Path=/payments/**
        - id: order-service
          uri: http://order-service.sheshan.local:8081
          predicates:
            - Path=/orders/**